<?php

return [
    'title' => 'Progression de lecture et statistiques Athkar et Coran',
    'updated' => 'Cette précision a été ajoutée le 13 septembre 2026.',
    'records' => 'Lorsque vous cochez volontairement un verset du Coran ou modifiez un compteur de répétitions des Athkar, SalaTime enregistre l’identifiant de l’élément, le jour civil local choisi et son état coché ou son nombre de répétitions. Si vous êtes connecté, ces données sont envoyées au service de comptes SalaTime et enregistrées dans sa base de données sous votre compte, avec les identifiants techniques, révisions et horodatages nécessaires à la synchronisation des modifications et à la prévention des doublons. Ces données peuvent révéler des informations sur votre pratique religieuse.',
    'purpose' => 'Cet historique vous permet de retrouver votre progression sur un autre appareil connecté à votre compte. L’application en déduit vos statistiques de lecture : totaux quotidiens et hebdomadaires, Athkar terminés, versets et sourates du Coran, progression générale et jours d’activité consécutifs. Ouvrir un écran de lecture ne marque pas automatiquement un élément comme lu. Ces données sont distinctes des préférences d’affichage du lecteur et ne sont pas envoyées à Google dans le cadre de la connexion Google.',
    'guest' => 'Le suivi des lectures fonctionne aussi sans compte. Les lectures effectuées en mode invité restent sur l’appareil et ne sont pas fusionnées automatiquement avec un compte lors de la connexion. Les modifications réalisées hors connexion sont conservées localement puis synchronisées lorsque la connexion au compte est de nouveau disponible.',
    'retention' => 'Décocher un élément ou remettre un compteur à zéro synchronise une valeur zéro afin que vos autres appareils appliquent la même modification. Le serveur conserve ces enregistrements à zéro et les données de synchronisation tant que le compte existe, pour préserver les remises à zéro et éviter de réappliquer d’anciennes modifications.',
    'deletion' => 'La suppression de votre compte SalaTime depuis les paramètres du compte dans l’application efface de la base active l’historique des lectures synchronisées et les données de synchronisation, avec les autres données du compte. Une simple déconnexion ne les supprime pas. Les copies locales des lectures et l’historique invité restent sur l’appareil. La politique générale ci-dessous décrit la conservation des sauvegardes.',
];
