<?php

return [
    'title' => 'Progreso de lectura y estadísticas de Athkar y del Corán',
    'updated' => 'Esta aclaración se añadió el 13 de septiembre de 2026.',
    'records' => 'Cuando marca expresamente un versículo del Corán como leído o modifica un contador de repeticiones de Athkar, SalaTime guarda el identificador del elemento, el día del calendario local elegido y su estado de lectura o número de repeticiones. Mientras tiene la sesión iniciada, estos datos se envían al servicio de cuentas de SalaTime y se almacenan en su base de datos bajo su cuenta, junto con los identificadores técnicos, revisiones y marcas de tiempo necesarios para sincronizar los cambios y evitar actualizaciones duplicadas. Estos registros pueden revelar información sobre su práctica religiosa.',
    'purpose' => 'Este historial permite recuperar su progreso en otro dispositivo conectado a su cuenta. La aplicación calcula a partir de él sus estadísticas de lectura: totales diarios y semanales, Athkar completados, versículos y suras del Corán, progreso general y días consecutivos de actividad. Abrir una pantalla de lectura no marca automáticamente ningún elemento como leído. Estos registros son distintos de las preferencias de visualización del lector y no se envían a Google como parte del inicio de sesión con Google.',
    'guest' => 'Puede utilizar el seguimiento de lectura sin una cuenta. Las lecturas como invitado permanecen en el dispositivo y no se incorporan automáticamente a una cuenta al iniciar sesión. Los cambios realizados sin conexión se guardan localmente y se sincronizan cuando vuelve a estar disponible la conexión con la cuenta.',
    'retention' => 'Desmarcar un elemento o poner un contador a cero sincroniza un valor cero para que sus otros dispositivos apliquen el mismo cambio. El servidor conserva estos registros con valor cero y los registros de sincronización mientras exista la cuenta, para mantener los reinicios y evitar volver a aplicar cambios antiguos.',
    'deletion' => 'Eliminar su cuenta de SalaTime desde los ajustes de la cuenta en la aplicación borra de la base de datos activa el historial de lectura sincronizado y los registros de sincronización, junto con los demás datos de la cuenta. Cerrar la sesión por sí solo no los elimina. Las copias locales de las lecturas y el historial de invitado permanecen en el dispositivo. La política general que figura a continuación describe la conservación de las copias de seguridad.',
];
