<?php

/*
|--------------------------------------------------------------------------
| Quran Surah Reference Data
|--------------------------------------------------------------------------
|
| Canonical mapping of Surah number (1-114) to its English name and the
| place of revelation. Used by the bulk reciter-audio importer to derive
| metadata for each uploaded file from its filename (which encodes the
| Surah number only).
|
*/

return [
    'suras' => [
        1 => ['name' => 'Al-Fatihah', 'revealed_place' => 'Makka'],
        2 => ['name' => 'Al-Baqarah', 'revealed_place' => 'Madina'],
        3 => ['name' => 'Aal-E-Imran', 'revealed_place' => 'Madina'],
        4 => ['name' => 'An-Nisa', 'revealed_place' => 'Madina'],
        5 => ['name' => 'Al-Maidah', 'revealed_place' => 'Madina'],
        6 => ['name' => 'Al-Anam', 'revealed_place' => 'Makka'],
        7 => ['name' => 'Al-Araf', 'revealed_place' => 'Makka'],
        8 => ['name' => 'Al-Anfal', 'revealed_place' => 'Madina'],
        9 => ['name' => 'At-Tawbah', 'revealed_place' => 'Madina'],
        10 => ['name' => 'Yunus', 'revealed_place' => 'Makka'],
        11 => ['name' => 'Hud', 'revealed_place' => 'Makka'],
        12 => ['name' => 'Yusuf', 'revealed_place' => 'Makka'],
        13 => ['name' => 'Ar-Rad', 'revealed_place' => 'Madina'],
        14 => ['name' => 'Ibrahim', 'revealed_place' => 'Makka'],
        15 => ['name' => 'Al-Hijr', 'revealed_place' => 'Makka'],
        16 => ['name' => 'An-Nahl', 'revealed_place' => 'Makka'],
        17 => ['name' => 'Al-Isra', 'revealed_place' => 'Makka'],
        18 => ['name' => 'Al-Kahf', 'revealed_place' => 'Makka'],
        19 => ['name' => 'Maryam', 'revealed_place' => 'Makka'],
        20 => ['name' => 'Taha', 'revealed_place' => 'Makka'],
        21 => ['name' => 'Al-Anbiya', 'revealed_place' => 'Makka'],
        22 => ['name' => 'Al-Hajj', 'revealed_place' => 'Madina'],
        23 => ['name' => 'Al-Muminun', 'revealed_place' => 'Makka'],
        24 => ['name' => 'An-Nur', 'revealed_place' => 'Madina'],
        25 => ['name' => 'Al-Furqan', 'revealed_place' => 'Makka'],
        26 => ['name' => 'Ash-Shuara', 'revealed_place' => 'Makka'],
        27 => ['name' => 'An-Naml', 'revealed_place' => 'Makka'],
        28 => ['name' => 'Al-Qasas', 'revealed_place' => 'Makka'],
        29 => ['name' => 'Al-Ankabut', 'revealed_place' => 'Makka'],
        30 => ['name' => 'Ar-Rum', 'revealed_place' => 'Makka'],
        31 => ['name' => 'Luqman', 'revealed_place' => 'Makka'],
        32 => ['name' => 'As-Sajda', 'revealed_place' => 'Makka'],
        33 => ['name' => 'Al-Ahzab', 'revealed_place' => 'Madina'],
        34 => ['name' => 'Saba', 'revealed_place' => 'Makka'],
        35 => ['name' => 'Fatir', 'revealed_place' => 'Makka'],
        36 => ['name' => 'Ya-Sin', 'revealed_place' => 'Makka'],
        37 => ['name' => 'As-Saffat', 'revealed_place' => 'Makka'],
        38 => ['name' => 'Sad', 'revealed_place' => 'Makka'],
        39 => ['name' => 'Az-Zumar', 'revealed_place' => 'Makka'],
        40 => ['name' => 'Ghafir', 'revealed_place' => 'Makka'],
        41 => ['name' => 'Fussilat', 'revealed_place' => 'Makka'],
        42 => ['name' => 'Ash-Shura', 'revealed_place' => 'Makka'],
        43 => ['name' => 'Az-Zukhruf', 'revealed_place' => 'Makka'],
        44 => ['name' => 'Ad-Dukhan', 'revealed_place' => 'Makka'],
        45 => ['name' => 'Al-Jathiyah', 'revealed_place' => 'Makka'],
        46 => ['name' => 'Al-Ahqaf', 'revealed_place' => 'Makka'],
        47 => ['name' => 'Muhammad', 'revealed_place' => 'Madina'],
        48 => ['name' => 'Al-Fath', 'revealed_place' => 'Madina'],
        49 => ['name' => 'Al-Hujurat', 'revealed_place' => 'Madina'],
        50 => ['name' => 'Qaf', 'revealed_place' => 'Makka'],
        51 => ['name' => 'Adh-Dhariyat', 'revealed_place' => 'Makka'],
        52 => ['name' => 'At-Tur', 'revealed_place' => 'Makka'],
        53 => ['name' => 'An-Najm', 'revealed_place' => 'Makka'],
        54 => ['name' => 'Al-Qamar', 'revealed_place' => 'Makka'],
        55 => ['name' => 'Ar-Rahman', 'revealed_place' => 'Madina'],
        56 => ['name' => 'Al-Waqiah', 'revealed_place' => 'Makka'],
        57 => ['name' => 'Al-Hadid', 'revealed_place' => 'Madina'],
        58 => ['name' => 'Al-Mujadila', 'revealed_place' => 'Madina'],
        59 => ['name' => 'Al-Hashr', 'revealed_place' => 'Madina'],
        60 => ['name' => 'Al-Mumtahina', 'revealed_place' => 'Madina'],
        61 => ['name' => 'As-Saff', 'revealed_place' => 'Madina'],
        62 => ['name' => 'Al-Jumuah', 'revealed_place' => 'Madina'],
        63 => ['name' => 'Al-Munafiqun', 'revealed_place' => 'Madina'],
        64 => ['name' => 'At-Taghabun', 'revealed_place' => 'Madina'],
        65 => ['name' => 'At-Talaq', 'revealed_place' => 'Madina'],
        66 => ['name' => 'At-Tahrim', 'revealed_place' => 'Madina'],
        67 => ['name' => 'Al-Mulk', 'revealed_place' => 'Makka'],
        68 => ['name' => 'Al-Qalam', 'revealed_place' => 'Makka'],
        69 => ['name' => 'Al-Haqqah', 'revealed_place' => 'Makka'],
        70 => ['name' => 'Al-Maarij', 'revealed_place' => 'Makka'],
        71 => ['name' => 'Nuh', 'revealed_place' => 'Makka'],
        72 => ['name' => 'Al-Jinn', 'revealed_place' => 'Makka'],
        73 => ['name' => 'Al-Muzzammil', 'revealed_place' => 'Makka'],
        74 => ['name' => 'Al-Muddaththir', 'revealed_place' => 'Makka'],
        75 => ['name' => 'Al-Qiyamah', 'revealed_place' => 'Makka'],
        76 => ['name' => 'Al-Insan', 'revealed_place' => 'Madina'],
        77 => ['name' => 'Al-Mursalat', 'revealed_place' => 'Makka'],
        78 => ['name' => 'An-Naba', 'revealed_place' => 'Makka'],
        79 => ['name' => 'An-Naziat', 'revealed_place' => 'Makka'],
        80 => ['name' => 'Abasa', 'revealed_place' => 'Makka'],
        81 => ['name' => 'At-Takwir', 'revealed_place' => 'Makka'],
        82 => ['name' => 'Al-Infitar', 'revealed_place' => 'Makka'],
        83 => ['name' => 'Al-Mutaffifin', 'revealed_place' => 'Makka'],
        84 => ['name' => 'Al-Inshiqaq', 'revealed_place' => 'Makka'],
        85 => ['name' => 'Al-Buruj', 'revealed_place' => 'Makka'],
        86 => ['name' => 'At-Tariq', 'revealed_place' => 'Makka'],
        87 => ['name' => 'Al-Ala', 'revealed_place' => 'Makka'],
        88 => ['name' => 'Al-Ghashiyah', 'revealed_place' => 'Makka'],
        89 => ['name' => 'Al-Fajr', 'revealed_place' => 'Makka'],
        90 => ['name' => 'Al-Balad', 'revealed_place' => 'Makka'],
        91 => ['name' => 'Ash-Shams', 'revealed_place' => 'Makka'],
        92 => ['name' => 'Al-Lail', 'revealed_place' => 'Makka'],
        93 => ['name' => 'Ad-Duha', 'revealed_place' => 'Makka'],
        94 => ['name' => 'Ash-Sharh', 'revealed_place' => 'Makka'],
        95 => ['name' => 'At-Tin', 'revealed_place' => 'Makka'],
        96 => ['name' => 'Al-Alaq', 'revealed_place' => 'Makka'],
        97 => ['name' => 'Al-Qadr', 'revealed_place' => 'Makka'],
        98 => ['name' => 'Al-Bayyinah', 'revealed_place' => 'Madina'],
        99 => ['name' => 'Az-Zalzalah', 'revealed_place' => 'Madina'],
        100 => ['name' => 'Al-Adiyat', 'revealed_place' => 'Makka'],
        101 => ['name' => 'Al-Qariah', 'revealed_place' => 'Makka'],
        102 => ['name' => 'At-Takathur', 'revealed_place' => 'Makka'],
        103 => ['name' => 'Al-Asr', 'revealed_place' => 'Makka'],
        104 => ['name' => 'Al-Humazah', 'revealed_place' => 'Makka'],
        105 => ['name' => 'Al-Fil', 'revealed_place' => 'Makka'],
        106 => ['name' => 'Quraish', 'revealed_place' => 'Makka'],
        107 => ['name' => 'Al-Maun', 'revealed_place' => 'Makka'],
        108 => ['name' => 'Al-Kawthar', 'revealed_place' => 'Makka'],
        109 => ['name' => 'Al-Kafirun', 'revealed_place' => 'Makka'],
        110 => ['name' => 'An-Nasr', 'revealed_place' => 'Madina'],
        111 => ['name' => 'Al-Masad', 'revealed_place' => 'Makka'],
        112 => ['name' => 'Al-Ikhlas', 'revealed_place' => 'Makka'],
        113 => ['name' => 'Al-Falaq', 'revealed_place' => 'Makka'],
        114 => ['name' => 'An-Nas', 'revealed_place' => 'Makka'],
    ],
];
